# Generated by Django 4.1.3 on 2022-12-13 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_supplierinfo_shops_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.shopdetail')),
                ('supplier_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplierinfo')),
            ],
        ),
    ]
